### ISSUE TITLE
test on video

### ISSUE THREAD

**Issue by gentle1212** [kocurvik/deep_vp#1]
How to use this repo to test on a video ?

**Comment by kocurvik** [comment]
You can use the model preview script. Please follow these instructions: https://github.com/kocurvik/deep_vp#model-preview

The preview prints out the focal length and the horizon line as the video is processed. If you need a different type of output let me know and I might create a different script.

Note that to check the accuracy for BrnoCarPark and BrnoCompSpeed the scripts output a somewhat specific json file for calibration. So that all the calibration files can be compared with the files from the BrnoCompSpeed results.

**Comment by gentle1212** [comment]
@kocurvik  thanks for your reply. But preview script is only generating lines on a video where as I want to have speed estimation of vehicles in a video like this picture given below. can you please create a script for this and guide me.
![Screenshot (59)](https://user-images.githubusercontent.com/63908294/125400926-ef71a200-e3cb-11eb-9fde-7923373a96b7.png)

**Comment by kocurvik** [comment]
Well this repository only contains code for semi-automatic camera calibration. To measure speed you need full camera calibration, vehicle detection and tracking.

You can use the code from this repo to detect the focal length of the camera and its relative orientation to the road plane. You will then need one ground truth measurement on the road plane to then measure distances on the road plane. There are some other methods which are fully automatic but the code is not available.

Once you get the camera calibration done you can measure distances in the road plane. Then you need to detect and track vehicles and select a point for which you want to determine the speed.

I also have a [paper](https://rdcu.be/cmmIq) about speed estimation along with a published [code](https://github.com/kocurvik/retinanet_traffic_3D). The method only works when the observed roads are straight which seems to be the case from you image. You will still need to calibrate the camera. In the paper I use a [method](https://arxiv.org/abs/1702.06451) by Sochor et al. However the code for that method is not publicly available. You can try contacting the authors. Or you can try to use the method from this repo, but you will need to determine the scale in the calibration file manually. You can also try to manually determine the positions of vanishing points and create the whole calibration file manually.
