### ISSUE TITLE
BrnoCarPark dataset download

### ISSUE THREAD

**Issue by NewSignal** [kocurvik/deep_vp#3]
I noticed that the BrnoCarPark dataset you used is not public. Can you provide a download link.

**Comment by kocurvik** [comment]
The website of the research group that published the dataset is offline since around summer 2020. So you have to contact the first author of the dataset paper at ibartl@fit.vutbr.cz

He will provide you with a link. I would give it to you myself, but I am not sure of the licensing policy of the authors so it would be better if you contact authors yourself.
